# Copyright 2026 Thousand Brains Project
#
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

"""Stitch per-experiment reports into a single index.md."""

from __future__ import annotations

from tools.dissertation_analysis.experiments import ExperimentReport


REPORT_ORDER = {
    "exp1": 10,
    "exp2": 20,
    "exp4": 30,
    "exp6": 40,
    "exp3": 50,
    "surface_unsupervised": 60,
    "exp5": 70,
}


def build_index(reports: list[ExperimentReport], output_dir: Path) -> Path:
    reports = sorted(
        reports,
        key=lambda r: (REPORT_ORDER.get(r.name, 999), r.title),
    )
    lines: list[str] = [
        "# Dissertation Analysis Index",
        "",
        "Auto-generated by `python -m tools.dissertation_analysis`.",
        "",
    ]
    for r in reports:
        lines.append(f"## {r.title}")
        if r.missing:
            lines.append("_Not executed — see § discussion._")
            if r.missing_reason:
                lines.append(f"_{r.missing_reason}_")
        else:
            lines.append(
                f"See [{r.relative_dir}/summary.md]({r.relative_dir}/summary.md)."
            )
            for fig in r.figures:
                lines.append(f"![]({r.relative_dir}/{fig})")
        lines.append("")
    out_path = output_dir / "index.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    return out_path
